### ISSUE TITLE
Release 1.0.2 to the community site

### ISSUE THREAD

**Issue by tas50** [jtimberman/smartmontools-cookbook#6]
Any chance you can push the latest release up to the community site?

-Tim

**Comment by bkw** [comment]
+1

**Comment by bkw** [comment]
Maybe a more detailed explanation is in order: Without the virtualization bypass of #5, any cookbook including smartmontools as a dependency will fail in vagrant and thus test-kitchen.
I already have 5 cookbooks all special casing smartmontools via Berksfile, only because they feature an integration test that includes a cookbook, which uses smartmontools.

A release on supermarket would be so much more convenient and much appreciated.

**Comment by jtimberman** [comment]
Wow. I am terrible. I've uploaded 1.0.2 to the Supermarket.

**Comment by jtimberman** [comment]
I've also made @tas50 a collaborator on this repository and the cookbook on the supermarket. :cake:

**Comment by bkw** [comment]
You are by no means terrible, but very awesome instead.
Thank You!
